# Generated by Django 2.0 on 2018-01-08 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20180107_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='contact_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_us',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_us',
            name='question',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
