# Generated by Django 2.0 on 2018-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20180108_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='register',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
