# Generated by Django 2.0 on 2018-01-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20180111_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Register',
        ),
    ]
